title: dtourolle portfolio
email: duncan2911(@)outllok.com
description: >- # this means to ignore newlines until "baseurl:"
 This is a collection of projects I have created as hobbies in my free time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dtourolle.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:slug.html

  
favicon: "logo.jfif" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
